modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "LGPL-3.0"

# PAS de [[mixins]] ici — enregistrement via IMixinConnector
# pour éviter l'interférence de Sinytra Connector

[[mods]]
    modId = "stacktonearbychests"
    version = "${version}"
    displayName = "Stack to Nearby Chests"
    description = '''
A client-side ONLY mod, adds the quick stacking and restocking features from Terraria into Minecraft.
'''
    logoFile = "assets/stacktonearbychests/icon.png"
    authors = "xiaocihua"

    [mods.contact]
        homepage = "https://github.com/xiaocihua"
        sources  = "https://github.com/xiaocihua/stack-to-nearby-chests"
        issues   = "https://github.com/xiaocihua/stack-to-nearby-chests/issues"

[[dependencies.stacktonearbychests]]
    modId      = "neoforge"
    type       = "required"
    versionRange = "${neo_version_range}"
    ordering   = "NONE"
    side       = "CLIENT"

[[dependencies.stacktonearbychests]]
    modId      = "minecraft"
    type       = "required"
    versionRange = "${minecraft_version_range}"
    ordering   = "NONE"
    side       = "CLIENT"

[[dependencies.stacktonearbychests]]
    modId      = "emi"
    type       = "optional"
    versionRange = "*"
    ordering   = "NONE"
    side       = "CLIENT"

[[dependencies.stacktonearbychests]]
    modId      = "roughlyenoughitems"
    type       = "optional"
    versionRange = "*"
    ordering   = "NONE"
    side       = "CLIENT"